/**
 * Cross-app onboarding types.
 *
 * Supports three onboarding paths:
 *   - parent_initiated  — parent generates an invite code, child enters it in the Safety app
 *   - child_initiated   — child submits a parent email, parent approves via web link
 *   - school_initiated  — school admin bulk-provisions children via SIS / Clever / ClassLink
 */

export type OnboardingPath =
  | "parent_initiated"
  | "child_initiated"
  | "school_initiated";

/** Short-lived 6-character alphanumeric code generated by a parent. */
export interface InviteCode {
  /** The uppercase 6-character code that the child enters in the app. */
  code: string;
  /** UUID of the family group the code belongs to. */
  group_id: string;
  /** UUID of the parent who generated the code. */
  created_by: string;
  /** ISO-8601 timestamp — code expires after 48 hours. */
  expires_at: string;
}

/** Parental approval request created when a child submits a parent email. */
export interface ParentApprovalRequest {
  /** UUID of the child user awaiting approval. */
  child_id: string;
  /** Email address of the parent who will receive the approval link. */
  parent_email: string;
  /** Lifecycle status of the approval request. */
  status: "pending" | "approved" | "denied";
}
