"""Seed data for AI Literacy modules and questions."""

SEED_MODULES = [
    {
        "title": "What is AI?",
        "description": "Learn what artificial intelligence is, how it works, and where you encounter it every day.",
        "category": "fundamentals",
        "difficulty_level": "beginner",
        "min_age": 6,
        "max_age": 18,
        "order_index": 1,
        "questions": [
            {
                "question_text": "What does AI stand for?",
                "question_type": "multiple_choice",
                "options": [
                    "Automatic Internet",
                    "Artificial Intelligence",
                    "Advanced Information",
                    "Applied Integration",
                ],
                "correct_answer": "Artificial Intelligence",
                "explanation": "AI stands for Artificial Intelligence — computer systems designed to perform tasks that normally require human thinking.",
                "order_index": 1,
            },
            {
                "question_text": "AI can learn from data and improve over time.",
                "question_type": "true_false",
                "options": ["True", "False"],
                "correct_answer": "True",
                "explanation": "AI systems use machine learning to get better at tasks by finding patterns in large amounts of data.",
                "order_index": 2,
            },
            {
                "question_text": "Which of these is an example of AI?",
                "question_type": "multiple_choice",
                "options": [
                    "A regular calculator",
                    "A voice assistant like Siri or Alexa",
                    "A light switch",
                    "A paper notebook",
                ],
                "correct_answer": "A voice assistant like Siri or Alexa",
                "explanation": "Voice assistants use AI to understand your speech and respond with helpful answers.",
                "order_index": 3,
            },
        ],
    },
    {
        "title": "AI Safety Basics",
        "description": "Understand the basics of staying safe when using AI tools like chatbots and image generators.",
        "category": "safety",
        "difficulty_level": "beginner",
        "min_age": 8,
        "max_age": 18,
        "order_index": 2,
        "questions": [
            {
                "question_text": "Is it safe to share your home address with an AI chatbot?",
                "question_type": "multiple_choice",
                "options": [
                    "Yes, AI keeps everything private",
                    "No, you should never share personal details with AI",
                    "Only if the AI asks nicely",
                    "Only on weekdays",
                ],
                "correct_answer": "No, you should never share personal details with AI",
                "explanation": "Never share personal information like your address, phone number, or school with AI tools. The data could be stored or shared.",
                "order_index": 1,
            },
            {
                "question_text": "Everything an AI chatbot says is always true.",
                "question_type": "true_false",
                "options": ["True", "False"],
                "correct_answer": "False",
                "explanation": "AI can make mistakes or 'hallucinate' — generating information that sounds right but is actually wrong. Always double-check important facts.",
                "order_index": 2,
            },
        ],
    },
    {
        "title": "Privacy & Data",
        "description": "Learn how AI uses your data, why privacy matters, and how to protect your personal information online.",
        "category": "privacy",
        "difficulty_level": "intermediate",
        "min_age": 10,
        "max_age": 18,
        "order_index": 3,
        "questions": [
            {
                "question_text": "What happens to the text you type into an AI chatbot?",
                "question_type": "multiple_choice",
                "options": [
                    "It disappears immediately",
                    "It may be stored and used to improve the AI",
                    "It is printed on paper",
                    "Nothing at all",
                ],
                "correct_answer": "It may be stored and used to improve the AI",
                "explanation": "Many AI companies store your conversations and may use them to train future versions of their AI. That is why you should be careful about what you share.",
                "order_index": 1,
            },
            {
                "question_text": "You should read the privacy policy before using a new AI tool.",
                "question_type": "true_false",
                "options": ["True", "False"],
                "correct_answer": "True",
                "explanation": "Privacy policies tell you how your data will be collected, stored, and used. Understanding this helps you make informed choices.",
                "order_index": 2,
            },
            {
                "question_text": "Which is the best way to protect your privacy when using AI?",
                "question_type": "multiple_choice",
                "options": [
                    "Use your real name and birthday in every chat",
                    "Share as little personal information as possible",
                    "Give the AI your parents' credit card number",
                    "Post your AI conversations on social media",
                ],
                "correct_answer": "Share as little personal information as possible",
                "explanation": "The less personal information you share with AI tools, the better protected your privacy will be.",
                "order_index": 3,
            },
        ],
    },
    {
        "title": "Critical Thinking with AI",
        "description": "Develop skills to evaluate AI-generated content and think critically about AI outputs.",
        "category": "critical_thinking",
        "difficulty_level": "intermediate",
        "min_age": 10,
        "max_age": 18,
        "order_index": 4,
        "questions": [
            {
                "question_text": "If an AI writes an essay for you, should you submit it as your own work?",
                "question_type": "multiple_choice",
                "options": [
                    "Yes, AI did the hard work",
                    "No, that would be dishonest and you would not learn anything",
                    "Only if no one finds out",
                    "Only for easy assignments",
                ],
                "correct_answer": "No, that would be dishonest and you would not learn anything",
                "explanation": "Submitting AI-generated work as your own is a form of academic dishonesty. AI should be a tool to help you learn, not to replace your thinking.",
                "order_index": 1,
            },
            {
                "question_text": "AI systems can have biases built into them.",
                "question_type": "true_false",
                "options": ["True", "False"],
                "correct_answer": "True",
                "explanation": "AI learns from data created by humans, so it can pick up human biases. It is important to question AI outputs and think critically.",
                "order_index": 2,
            },
        ],
    },
    {
        "title": "Deepfakes & Misinformation",
        "description": "Learn to recognize AI-generated fake images, videos, and text, and understand why they can be harmful.",
        "category": "misinformation",
        "difficulty_level": "advanced",
        "min_age": 12,
        "max_age": 18,
        "order_index": 5,
        "questions": [
            {
                "question_text": "What is a deepfake?",
                "question_type": "multiple_choice",
                "options": [
                    "A very deep swimming pool",
                    "An AI-generated fake image, video, or audio that looks real",
                    "A type of computer virus",
                    "A new social media platform",
                ],
                "correct_answer": "An AI-generated fake image, video, or audio that looks real",
                "explanation": "Deepfakes use AI to create realistic-looking fake media. They can be used to spread misinformation or impersonate people.",
                "order_index": 1,
            },
            {
                "question_text": "You can always tell if an image is AI-generated just by looking at it.",
                "question_type": "true_false",
                "options": ["True", "False"],
                "correct_answer": "False",
                "explanation": "AI-generated images are getting better all the time, and many look very realistic. You may need fact-checking tools and critical thinking to spot fakes.",
                "order_index": 2,
            },
            {
                "question_text": "What should you do if you see something online that looks suspicious?",
                "question_type": "multiple_choice",
                "options": [
                    "Share it immediately with everyone",
                    "Check multiple reliable sources before believing or sharing it",
                    "Assume it must be true because it is online",
                    "Ignore it completely",
                ],
                "correct_answer": "Check multiple reliable sources before believing or sharing it",
                "explanation": "Always verify information from multiple trusted sources before believing or sharing it. This helps stop the spread of misinformation.",
                "order_index": 3,
            },
        ],
    },
    {
        "title": "Responsible AI Use",
        "description": "Learn how to use AI tools responsibly, ethically, and in ways that benefit everyone.",
        "category": "ethics",
        "difficulty_level": "advanced",
        "min_age": 12,
        "max_age": 18,
        "order_index": 6,
        "questions": [
            {
                "question_text": "What is the most responsible way to use AI for homework?",
                "question_type": "multiple_choice",
                "options": [
                    "Copy everything the AI generates",
                    "Use AI to help you understand concepts, then write in your own words",
                    "Never use AI at all",
                    "Let AI do your homework while you play games",
                ],
                "correct_answer": "Use AI to help you understand concepts, then write in your own words",
                "explanation": "AI is a great learning tool when used responsibly. Use it to explore ideas and understand topics, but always do your own thinking and writing.",
                "order_index": 1,
            },
            {
                "question_text": "It is okay to use AI to create fake content about real people.",
                "question_type": "true_false",
                "options": ["True", "False"],
                "correct_answer": "False",
                "explanation": "Creating fake content about real people can be harmful, hurtful, and in some cases illegal. Always use AI ethically and respect others.",
                "order_index": 2,
            },
        ],
    },
]
