"""Creative module FastAPI router — AI art, stories, stickers, drawings."""

from uuid import UUID

import structlog
from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession

from src.auth.middleware import get_current_user
from src.billing.feature_gate import check_feature_gate
from src.creative import service
from src.creative.schemas import (
    ArtGenerationCreate,
    ArtGenerationResponse,
    DrawingAssetCreate,
    DrawingAssetResponse,
    StickerPackResponse,
    StickerResponse,
    StoryCreationCreate,
    StoryCreationResponse,
    StoryTemplateResponse,
)
from src.database import get_db
from src.schemas import GroupContext

logger = structlog.get_logger()

router = APIRouter(dependencies=[Depends(check_feature_gate("creative_tools"))])


# ---------------------------------------------------------------------------
# Art generation
# ---------------------------------------------------------------------------


@router.post("/art", response_model=ArtGenerationResponse, status_code=201)
async def generate_art(
    data: ArtGenerationCreate,
    auth: GroupContext = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Generate AI art for a member."""
    art = await service.generate_art(
        db,
        member_id=data.member_id,
        group_id=data.group_id,
        prompt=data.prompt,
        model=data.model,
    )
    await db.commit()
    await db.refresh(art)
    return art


@router.get("/art/{member_id}", response_model=list[ArtGenerationResponse])
async def list_member_art(
    member_id: UUID,
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=50, ge=1, le=100),
    auth: GroupContext = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List AI art generated by a member."""
    return await service.list_member_art(db, member_id, offset=offset, limit=limit)


# ---------------------------------------------------------------------------
# Story templates
# ---------------------------------------------------------------------------


@router.get("/templates", response_model=list[StoryTemplateResponse])
async def get_story_templates(
    age_tier: str | None = Query(default=None),
    auth: GroupContext = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Return story templates, optionally filtered by age tier."""
    return await service.get_story_templates(db, age_tier=age_tier)


# ---------------------------------------------------------------------------
# Story creation
# ---------------------------------------------------------------------------


@router.post("/stories", response_model=StoryCreationResponse, status_code=201)
async def create_story(
    data: StoryCreationCreate,
    auth: GroupContext = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Create a story for a member."""
    member_id = data.member_id or auth.user_id
    story = await service.create_story(
        db,
        member_id=member_id,
        content=data.content,
        template_id=data.template_id,
    )
    await db.commit()
    await db.refresh(story)
    return story


@router.get("/stories/{member_id}", response_model=list[StoryCreationResponse])
async def list_member_stories(
    member_id: UUID,
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=50, ge=1, le=100),
    auth: GroupContext = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List stories created by a member."""
    return await service.list_member_stories(db, member_id, offset=offset, limit=limit)


# ---------------------------------------------------------------------------
# Drawings
# ---------------------------------------------------------------------------


@router.post("/drawings", response_model=DrawingAssetResponse, status_code=201)
async def save_drawing(
    data: DrawingAssetCreate,
    auth: GroupContext = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Save a freehand drawing for a member."""
    from src.dependencies import resolve_group_id

    member_id = data.member_id or auth.user_id
    group_id = data.group_id or resolve_group_id(None, auth)
    drawing = await service.save_drawing(
        db,
        member_id=member_id,
        group_id=group_id,
        image_url=data.image_url,
    )
    await db.commit()
    await db.refresh(drawing)
    return drawing


@router.get("/drawings/{member_id}", response_model=list[DrawingAssetResponse])
async def list_member_drawings(
    member_id: UUID,
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=50, ge=1, le=100),
    auth: GroupContext = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List drawings created by a member."""
    return await service.list_member_drawings(db, member_id, offset=offset, limit=limit)


# ---------------------------------------------------------------------------
# Stickers
# ---------------------------------------------------------------------------


@router.post("/stickers", response_model=StickerResponse, status_code=201)
async def create_custom_sticker(
    data: DrawingAssetCreate,  # reuse image_url field
    auth: GroupContext = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Create a custom sticker in the member's personal pack."""
    member_id = data.member_id or auth.user_id
    sticker = await service.create_custom_sticker(
        db,
        member_id=member_id,
        image_url=data.image_url,
    )
    await db.commit()
    await db.refresh(sticker)
    return sticker


@router.get("/sticker-packs", response_model=list[StickerPackResponse])
async def get_sticker_packs(
    include_user_packs: bool = Query(default=False),
    auth: GroupContext = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List curated sticker packs, optionally including the member's personal packs."""
    member_id = auth.user_id if include_user_packs else None
    return await service.get_sticker_packs(
        db,
        include_user_packs=include_user_packs,
        member_id=member_id,
    )


# ---------------------------------------------------------------------------
# Post to feed
# ---------------------------------------------------------------------------


@router.post("/{asset_type}/{asset_id}/post-to-feed", status_code=200)
async def post_to_feed(
    asset_type: str,
    asset_id: UUID,
    auth: GroupContext = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Mark a story or drawing as posted to the social feed."""
    asset = await service.post_to_feed(db, asset_type=asset_type, asset_id=asset_id)
    await db.commit()
    return {"posted_to_feed": True, "asset_type": asset_type, "asset_id": str(asset_id)}
